[tool.poetry]
name = "vote_alg_runner"
version = "0.1.0"
description = ""
authors = ["Dmitry <dimafilin6@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
